version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    env_file: .env
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_DATABASE: linq
      PORT: 7777
      TZ: Asia/Tokyo
    ports:
      - 7777:7777
    volumes:
      - .:/app
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linq
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
